### ISSUE TITLE
Error on using  blinky_gui.py 

### ISSUE THREAD

**Issue by NIDHIPANDA** [dilawar/eye-blink-detector#6]
Hello Dilawar,  I am trying to run your blinky_gui.py code on Ubuntu16.04 using virtual environment with Python 3.5 and OpenCv 3.3. version. I am taking one .mp4 file as video input. On running I am getting this error. 
![screenshot from 2018-03-31 04-15-33](https://user-images.githubusercontent.com/23721905/38146576-33a5fa88-346c-11e8-9339-2e15d76e02b2.png)
  Can you please help me with this.

**Comment by dilawar** [comment]
Can you upload the MP4 or share it via drive?

I haven't tested it with python3. Try with python2.7 as well.

⁣Sent from Blue ​

**Comment by NIDHIPANDA** [comment]
Thank you so much for your reply. I have sent video file on your mail ID mentioned in your code as I don't know how to share it here.

**Comment by dilawar** [comment]
Please reopen it if it does not work. openv>3.0.0 has major changes in function return values/types. Few other things can break as well.

**Comment by NIDHIPANDA** [comment]
Thank you for the change in script. Now it worked nicely upto 4th blink . But after 4th blink it is showing following error.
![screenshot from 2018-03-31 20-05-56](https://user-images.githubusercontent.com/23721905/38161674-58b9403e-34f1-11e8-8099-0180d37eb368.png)
One more thing I am new in this area. Can you please tell me how to debug the code to understand it better (like we do in MATLAB) by using virtual environment. As mentioned earlier I am using openCv 3.3 and python 3.5.2 on virtual environment. I tried to use IDEL but the python cell showed error in importing cv2. Is there any other way by directly using terminal window of ubuntu 16.04.

**Comment by dilawar** [comment]
There are tools such as spyder https://pythonhosted.org/spyder/installation.html .

Once you are comfortable with python, you usually don't need debugger. These errors are good enough to fix the issue.
